### ISSUE TITLE
Too specific peerDependencies

### ISSUE THREAD

**Issue by mkazlauskas** [webcomputing/inversify-components#2]
Hello, first of all, nice package - exactly what I was looking for.

The issue is that I believe the *inversify* in `peerDependencies` you have listed is too specific - I suggest using **^** or **~** range syntax.

**Comment by antoniusostermann** [comment]
Hey,

thanks for using inversify-components! I never imagined inversify-components would be useful for other packages than AssistantJS (https://github.com/webcomputing/AssistantJS).

As far as I remeber, I got some compatibility issues with some inversify versions. You are very welcome to check this out and open a PR if inversify-components works well with other/newer versions. Alternatively, I possibly get back on this in the next two months.

**Comment by antoniusostermann** [comment]
Closed thanks to @xavierraffin https://github.com/webcomputing/inversify-components/pull/5
